# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_createmodels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='inline',
        ),
        migrations.AddField(
            model_name='model',
            name='inlines',
            field=models.ManyToManyField(related_name='_model_inlines_+', to='django_createmodels.Model'),
        ),
    ]
