# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_createmodels', '0002_auto_20161127_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='inlines',
            field=models.ManyToManyField(blank=True, related_name='_model_inlines_+', to='django_createmodels.Model'),
        ),
    ]
