# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_createmodels', '0005_field_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='max_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
