# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_createmodels', '0006_auto_20161127_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='default',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='field',
            name='reference',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='django_createmodels.Model'),
        ),
    ]
