# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_createmodels', '0008_auto_20161127_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[(b'BooleanField', b'BooleanField'), (b'CharField', b'CharField'), (b'DateTimeField', b'DateTimeField'), (b'DateField', b'DateField'), (b'ForeignKey', b'ForeignKey'), (b'ImageFieldIntegerField', b'ImageFieldIntegerField'), (b'NumericField', b'NumericField'), (b'TextField', b'TextField')], max_length=30),
        ),
    ]
