# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('createmodels', '0001_initial'), ('createmodels', '0002_auto_20161127_0350'), ('createmodels', '0003_auto_20161127_0352'), ('createmodels', '0004_auto_20161127_0402'), ('createmodels', '0005_field_max_length'), ('createmodels', '0006_auto_20161127_0404'), ('createmodels', '0007_auto_20161127_0406'), ('createmodels', '0008_auto_20161127_0407'), ('createmodels', '0009_auto_20161127_0408'), ('createmodels', '0010_auto_20161127_1729'), ('createmodels', '0011_auto_20161128_0350'), ('createmodels', '0012_model_verbose_name'), ('createmodels', '0013_field_admin_readonly'), ('createmodels', '0014_model_list_per_page'), ('createmodels', '0015_auto_20161128_0817'), ('createmodels', '0016_field_choices')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('verbose', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[(b'BooleanField', b'BooleanField'), (b'CharField', b'CharField'), (b'DateTimeField', b'DateTimeField'), (b'DateField', b'DateField'), (b'ImageFieldIntegerField', b'ImageFieldIntegerField'), (b'NumericField', b'NumericField'), (b'TextField', b'TextField')], max_length=30)),
                ('is_fk', models.BooleanField()),
                ('is_pk', models.BooleanField()),
                ('allow_null', models.BooleanField()),
                ('allow_blank', models.BooleanField()),
                ('use_for_self', models.BooleanField()),
                ('use_for_ordering', models.BooleanField()),
                ('admin_search', models.BooleanField()),
                ('admin_filter', models.BooleanField()),
                ('admin_list', models.BooleanField()),
                ('default', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('inlines', models.ManyToManyField(blank=True, to=b'createmodels.Model')),
                ('verbose_name', models.CharField(blank=True, max_length=200, null=True)),
                ('list_per_page', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='createmodels.Model'),
        ),
        migrations.AddField(
            model_name='field',
            name='model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='createmodels.Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='max_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='default',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='field',
            name='default',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[(b'BooleanField', b'BooleanField'), (b'CharField', b'CharField'), (b'DateTimeField', b'DateTimeField'), (b'DateField', b'DateField'), (b'ForeignKey', b'ForeignKey'), (b'ImageFieldIntegerField', b'ImageFieldIntegerField'), (b'NumericField', b'NumericField'), (b'TextField', b'TextField')], max_length=30),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[(b'BooleanField', b'BooleanField'), (b'CharField', b'CharField'), (b'DateTimeField', b'DateTimeField'), (b'DateField', b'DateField'), (b'ForeignKey', b'ForeignKey'), (b'ImageField', b'ImageField'), (b'IntegerField', b'IntegerField'), (b'NumericField', b'NumericField'), (b'TextField', b'TextField')], max_length=30),
        ),
        migrations.RenameField(
            model_name='field',
            old_name='verbose',
            new_name='verbose_name',
        ),
        migrations.AddField(
            model_name='field',
            name='admin_readonly',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[(b'BooleanField', b'BooleanField'), (b'CharField', b'CharField'), (b'DateTimeField', b'DateTimeField'), (b'DateField', b'DateField'), (b'DecimalField', b'DecimalField'), (b'ForeignKey', b'ForeignKey'), (b'ImageField', b'ImageField'), (b'IntegerField', b'IntegerField'), (b'TextField', b'TextField')], max_length=30),
        ),
        migrations.AlterField(
            model_name='field',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='choices',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
