# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('verbose', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[(b'BooleanField', b'BooleanField'), (b'CharField', b'CharField'), (b'DateTimeField', b'DateTimeField'), (b'DateField', b'DateField'), (b'ImageFieldIntegerField', b'ImageFieldIntegerField'), (b'NumericField', b'NumericField'), (b'TextField', b'TextField')], max_length=30)),
                ('is_fk', models.BooleanField()),
                ('is_pk', models.BooleanField()),
                ('allow_null', models.BooleanField()),
                ('allow_blank', models.BooleanField()),
                ('use_for_self', models.BooleanField()),
                ('use_for_ordering', models.BooleanField()),
                ('admin_search', models.BooleanField()),
                ('admin_filter', models.BooleanField()),
                ('admin_list', models.BooleanField()),
                ('default', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('inline', models.ManyToManyField(related_name='_model_inline_+', to='createmodels.Model')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createmodels.Model'),
        ),
    ]
