# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createmodels', '0011_auto_20161128_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
