# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createmodels', '0012_model_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='admin_readonly',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
