# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createmodels', '0013_field_admin_readonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='list_per_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
