# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createmodels', '0014_model_list_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[(b'BooleanField', b'BooleanField'), (b'CharField', b'CharField'), (b'DateTimeField', b'DateTimeField'), (b'DateField', b'DateField'), (b'DecimalField', b'DecimalField'), (b'ForeignKey', b'ForeignKey'), (b'ImageField', b'ImageField'), (b'IntegerField', b'IntegerField'), (b'TextField', b'TextField')], max_length=30),
        ),
        migrations.AlterField(
            model_name='field',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='inlines',
            field=models.ManyToManyField(blank=True, to='createmodels.Model'),
        ),
    ]
