# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createmodels', '0015_auto_20161128_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='choices',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
